name: Create Pre-Release On Merge (app)

on:
  push:
    branches:
      - release
    paths:
      - app/src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '21'
          cache: 'gradle'

      - run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Create Debug APK
        run: ./gradlew assembleDebug

      - run: mv app/build/outputs/apk/debug/*.apk Blocktopograph.apk

      - uses: ncipollo/release-action@v1.14.0
        with:
          prerelease: true
          name: Nightly Build
          artifacts: Blocktopograph.apk
          tag: nightly
          allowUpdates: true
          artifactErrorsFailBuild: true