name: Create Pre-Release On Merge (app)

on:
  push:
    branches:
      - dev
    paths:
      - app
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'
          cache: 'gradle'

      - run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Create Debug APK
        run: ./gradlew assembleDebug

      - run: mv app/build/outputs/apk/debug/*.apk Blocktopograph.apk

      - uses: ncipollo/release-action@v1
        with:
          prerelease: true
          name: Nightly Build
          bodyFile: release_notes.md
          artifacts: Blocktopograph.apk
          tag: nightly
          allowUpdates: true
          artifactErrorsFailBuild: true