name: Create Pre-Release On Merge (app)

on:
  push:
    branches:
      - release
    paths:
      - app/src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
         submodules: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
         distribution: 'microsoft'
         java-version: '11'
         cache: 'gradle'

      - run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Create Debug APK
        run: ./gradlew assembleDebug

      - run: mv app/build/outputs/apk/debug/*.apk Blocktopograph.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Blocktopograph Debug APK
          path: Blocktopograph.apk